remote_theme: pmarsceill/just-the-docs
color_scheme: nil #nil or "dark"

title: Raspberry Pi 3B
description: Any Task, Any Goal, Get Things Done
url: "https://catamold.github.io"

author:
  name: Catalin Moldovan
  github: catamold