remote_theme: pmarsceill/just-the-docs
color_scheme: nil #nil or "dark"

title: Raspberry Pi Projects
description: Any Task, Any Goal, Get Things Done
url: "https://catamold.github.io"

author:
  name: Catalin Moldovan
  github: catamold
  
favicon: icons/favicon.ico
use_logo: true